plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.gms.google.services)
}

android {
    namespace 'com.example.chatappadmin'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.chatappadmin"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    packaging {
        resources {
            excludes += [
                    'META-INF/LICENSE.md',
                    'META-INF/LICENSE',
                    'META-INF/NOTICE.md',   // 🔥 Add this line
                    'META-INF/NOTICE'       // (optional) in case NOTICE is also duplicated
            ]
        }
    }

}

dependencies {
        implementation libs.appcompat
        implementation libs.material
        implementation libs.activity
        implementation libs.constraintlayout
        implementation libs.firebase.auth
        implementation libs.firebase.storage
        implementation libs.firebase.firestore
    implementation libs.firebase.database
    testImplementation libs.junit
        androidTestImplementation libs.ext.junit
        androidTestImplementation libs.espresso.core
        // Firebase Play Integrity API
        implementation 'com.google.android.play:integrity:1.2.0'
//        implementation 'com.github.yalantis:ucrop:2.2.6'
//        implementation 'de.hdodenhof:circleimageview:3.1.0'
        // Google reCAPTCHA API
        implementation 'com.google.android.gms:play-services-safetynet:18.0.1'
        implementation 'com.squareup.okhttp3:okhttp:4.9.0'
        implementation 'com.sun.mail:android-mail:1.6.7'
        implementation 'com.sun.mail:android-activation:1.6.7'
    implementation 'com.google.firebase:firebase-firestore:24.7.1'


    implementation 'com.github.bumptech.glide:glide:4.16.0'
        implementation 'com.squareup.picasso:picasso:2.71828'
    }